import type { Metadata } from "next";
import { Roboto, Babylonica } from "next/font/google";
import localFont from "next/font/local";
import { Header } from "@/components/layout";
import "./globals.css";
import { MainFooter } from "@/components/layout/Footer/MainFooter";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const babylonica = Babylonica({
  variable: "--font-script",
  subsets: ["latin"],
  weight: ["400"],
});

const axiforma = localFont({
  src: "../public/fonts/axiforma/Axiforma-Regular.woff2",
  variable: "--font-axiforma",
  weight: "400",
});

export const metadata: Metadata = {
  title: "WATCH BRASIL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body
        className={`${roboto.variable} ${babylonica.variable} ${axiforma.variable} antialiased`}
      >
        <Header />
        <main className="pt-16">{children}</main>
        <MainFooter />
      </body>
    </html>
  );
}
